### ISSUE TITLE
Move this repo to openSUSE?

### ISSUE THREAD

**Issue by gonzoleeman** [morbidrsa/fcoe-utils#4]
Hi Johannes!

It looks like this is the source for fcoe-utils for SUSE/openSUSE. Do you still want to own your own repo? If not, you could move it to openSUSE. If so, I could just clone it, but I hate to split if you're planning on maintaining it.

You can email me at SUSE email addr or reply here. Thanks.

**Comment by morbidrsa** [comment]
I think moving it to the openSUSE space is a good idea. I'll move it and add you as a maintainer.

**Comment by morbidrsa** [comment]
Done.

**Comment by gonzoleeman** [comment]
Thank you!

**Comment by gonzoleeman** [comment]
Hi. Did you add me as a maintainer? I can't seem to merge anything ...

**Comment by morbidrsa** [comment]
I added the openSUSE storage team as owner of this repository, but it looks like I can't change the permissions on it. Maybe @hreinecke can help?

**Comment by gonzoleeman** [comment]
> I added the openSUSE storage team as owner of this repository, but it looks like I can't change the permissions on it. Maybe @hreinecke can help?

Did you give permission to "storage" or to "storage-team"? I'm in the former. The latter is the Ceph team.

**Comment by gonzoleeman** [comment]
Never mind. I see you gave permission to the correct team (which both of us are on), but neither of us have "write" (commit) permission there. :) At least I don't. And it doesn't even list any "owner" on the team, so evidently even Hannes can't directly change it.

**Comment by gonzoleeman** [comment]
Marking as resolved.
